### ISSUE TITLE
Resource Exhaustion / Denial of Service 

### ISSUE THREAD

**Issue by dhs-aws** [ietf-scim-wg/draft-ietf-scim-cursor-pagination#1]
Creating this issue based on comments provided during the call for adoption:

How does the proposed specification address resource exhaustion or denial of service when multiple cursors are maintained over a period of time?

**Comment by aaronpk** [comment]
This might be better explained in a few sentences in the introduction, to provide more context for when this extension applies in the first place.

**Comment by dhs-aws** [comment]
Thanks Aaron.  As discussed on today's call we'll aim to get the changes into a draft ahead of the IETF116 deadline.
