### ISSUE TITLE
Cursor lifetime

### ISSUE THREAD

**Issue by andrewclymer** [ietf-scim-wg/draft-ietf-scim-cursor-pagination#11]
I've read the paging cursor, specification. How long can a client guarantee they can use the nextCursor value?

**Comment by ansg-aws** [comment]
It depends on the Server Implementor. The Server Provider Configuration exposes the "cursorTimeout" parameter to guarantee that clients can use the nextCursor value for the duration of Timeout period.

**Comment by andrewclymer** [comment]
Thanks, can't believe  I missed it
